repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: lint-placeholder
        name: Lint Placeholder
        entry: ./scripts/lint.sh
        language: script
        pass_filenames: false
      - id: test-placeholder
        name: Test Placeholder
        entry: ./scripts/test.sh
        language: script
        pass_filenames: false
