name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Run automated test suites
        id: run-tests
        run: npm test

      - name: Upload coverage report
        if: success() && hashFiles('coverage/lcov.info') != ''
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage
